[package]
name = "turbo_zk_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.27.0", features = ["full"] }

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "benchmarks"
harness = false
